### ISSUE TITLE
sql .select() 多个同一实体,查询报错

### ISSUE THREAD

**Issue by h619633675** [donet5/SqlSugar#906]
你好,我在项目中之前是一个一个字段select返回，今天试了一下直接select多个实体返回时出错了，下面是部分错误信息。

```
生成的 sql，在 navicat 中查询正常
-- paramter and sql:
SET @MethodConst0=2;

 SELECT  `a`.`InvitationCode` AS `AUserAccountMDO.InvitationCode` , `a`.`ID_Account` AS `AUserAccountMDO.IDAccount` , `a`.`ID_Parent` AS `AUserAccountMDO.IDParent` , `a`.`U_Phone` AS `AUserAccountMDO.UPhone` , `a`.`U_Password` AS `AUserAccountMDO.UPassword` , `a`.`SafePassword` AS `AUserAccountMDO.SafePassword` , `a`.`RegTime` AS `AUserAccountMDO.RegTime` , `a`.`Webname` AS `AUserAccountMDO.Webname` , `a`.`HeadImageUrl` AS `AUserAccountMDO.HeadImageUrl` , `a`.`InviteBackImg` AS `AUserAccountMDO.InviteBackImg` , `a`.`Sex` AS `AUserAccountMDO.Sex` , `a`.`U_Level` AS `AUserAccountMDO.ULevel` , `a`.`City` AS `AUserAccountMDO.City` , `a`.`CityCode` AS `AUserAccountMDO.CityCode` , `a`.`On_Off` AS `AUserAccountMDO.OnOff` , `a`.`IsPay` AS `AUserAccountMDO.IsPay` , `a`.`U_InsideType` AS `AUserAccountMDO.UInsideType` , `a`.`LevelUpdateTime` AS `AUserAccountMDO.LevelUpdateTime` , `b`.`InvitationCode` AS `AUserAccountMDO.InvitationCode` , `b`.`ID_Account` AS `AUserAccountMDO.IDAccount` , `b`.`ID_Parent` AS `AUserAccountMDO.IDParent` , `b`.`U_Phone` AS `AUserAccountMDO.UPhone` , `b`.`U_Password` AS `AUserAccountMDO.UPassword` , `b`.`SafePassword` AS `AUserAccountMDO.SafePassword` , `b`.`RegTime` AS `AUserAccountMDO.RegTime` , `b`.`Webname` AS `AUserAccountMDO.Webname` , `b`.`HeadImageUrl` AS `AUserAccountMDO.HeadImageUrl` , `b`.`InviteBackImg` AS `AUserAccountMDO.InviteBackImg` , `b`.`Sex` AS `AUserAccountMDO.Sex` , `b`.`U_Level` AS `AUserAccountMDO.ULevel` , `b`.`City` AS `AUserAccountMDO.City` , `b`.`CityCode` AS `AUserAccountMDO.CityCode` , `b`.`On_Off` AS `AUserAccountMDO.OnOff` , `b`.`IsPay` AS `AUserAccountMDO.IsPay` , `b`.`U_InsideType` AS `AUserAccountMDO.UInsideType` , `b`.`LevelUpdateTime` AS `AUserAccountMDO.LevelUpdateTime`  FROM `a_user_account` a Left JOIN `a_user_account` b ON ( `a`.`ID_Parent` = `b`.`ID_Account` )  Inner JOIN `a_user_order` c ON ( `a`.`ID_Account` = `c`.`ID_account` )    WHERE  (`c`.`ID_Group` like concat('%',@MethodConst0,'%'))   ORDER BY `c`.`ID_order` DESC LIMIT 0,10;
```

异常信息
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.ArgumentException: An item with the same key has already been added. Key: AUserAccountMDO.InvitationCode
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at SqlSugar.ContextMethods.DataReaderToDictionary(IDataReader reader, Type type)
   at SqlSugar.ContextMethods.DataReaderToList[T](IDataReader reader, Type tType, List`1 classProperties, List`1 reval)
   at SqlSugar.ContextMethods.DataReaderToList[T](IDataReader reader)
   at SqlSugar.QueryableProvider`1.GetData[TResult](Boolean isComplexModel, Type entityType, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetData[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToList[TResult]()
   at SqlSugar.QueryableProvider`1.ToList()
   at SqlSugar.QueryableProvider`1.ToPageList(Int32 pageIndex, Int32 pageSize)
   at SqlSugar.QueryableProvider`1.<>c__DisplayClass141_0.<ToPageList>b__0()
   at SqlSugar.UtilMethods.GetOldValue[T](T value, Action action)
   at SqlSugar.QueryableProvider`1.ToPageList(Int32 pageIndex, Int32 pageSize, Int32& totalNumber)
   at Online.DAL.Manage.BAUserOrderDAL.QueryFinanceOrderAsync(RequestPageDTO`1 pageWhere) in D:\Work\PrivateProject\MaYun\pin-tuan-api\src\Online.Server\Online.DAL\Manage\BAUserOrderDAL.cs:line 515
   at Online.BLL.Manage.FinanceOrderBLL.List(RequestPageDTO`1 pageWhere) in D:\Work\PrivateProject\MaYun\pin-tuan-api\src\Online.Server\Online.BLL\Manage\FinanceOrderBLL.cs:line 20
   at Online.Server.Controllers.Manage.FinanceOrderController.List(RequestPageDTO`1 pageWhere) in D:\Work\PrivateProject\MaYun\pin-tuan-api\src\Online.Server\Online.Server\Controllers\Manage\FinanceOrderController.cs:line 23
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

部分查询函数代码
```
var query = Conn.Queryable<AUserAccountMDO, AUserAccountMDO, AUserOrderMDO>((a, b, c) => new JoinQueryInfos(
                JoinType.Left, a.IDParent == b.IDAccount, JoinType.Inner, a.IDAccount == c.IDAccount
            ));
var querySelect = query.Select((a, b, c) => new
            {
                user = a,
                parentUser = b,
                //userOrder = c,
            });
// 异步与同步报错相同
int totalNumber = 0;
var list = querySelect.ToPageList(pageWhere.CurrPage, pageWhere.PageSize, ref totalNumber);

````

**Comment by h619633675** [comment]
``` 报错的 demo
var query = Conn.Queryable<UsernameDM, UsernameDM>((a, b) => new JoinQueryInfos(
           JoinType.Left, a.PId == b.Id
       ));
      var qselect = query.Select((a, b) => new
      {
          user = a,
          parentUser = b
      });
      var result = qselect.First();
```

``` 生成的 sql
database: test;
connectionString: database=test;server=localhost;port=3306;user id=root;password=666666;characterset=utf8mb4;allowuservariables=True;
-- paramter and sql:


 SELECT  `a`.`id` AS `UsernameDM.Id` , `a`.`username` AS `UsernameDM.Username` , `a`.`pid` AS `UsernameDM.PId` , `b`.`id` AS `UsernameDM.Id` , `b`.`username` AS `UsernameDM.Username` , `b`.`pid` AS `UsernameDM.PId`  FROM `username` a Left JOIN `username` b ON ( `a`.`pid` = `b`.`id` )     ORDER BY NOW()  LIMIT 0,1;
```

``` 异常信息

Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: UsernameDM.Id
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at SqlSugar.ContextMethods.DataReaderToDictionary(IDataReader reader, Type type)
   at SqlSugar.ContextMethods.DataReaderToList[T](IDataReader reader, Type tType, List`1 classProperties, List`1 reval)
   at SqlSugar.ContextMethods.DataReaderToList[T](IDataReader reader)
   at SqlSugar.QueryableProvider`1.GetData[TResult](Boolean isComplexModel, Type entityType, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetData[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToList[TResult]()
   at SqlSugar.QueryableProvider`1.ToList()
   at SqlSugar.QueryableProvider`1.First()
   at _014_SqlSugar测试sql.Demo.AliasSelect() in D:\Work\_my\myYun\demo_csharp\.net core3.1 web api 部分组件示例\014_SqlSugar测试sql\Program.cs:line 45
   at _014_SqlSugar测试sql.Demo..ctor() in D:\Work\_my\myYun\demo_csharp\.net core3.1 web api 部分组件示例\014_SqlSugar测试sql\Program.cs:line 29
   at _014_SqlSugar测试sql.Program.Main(String[] args) in D:\Work\_my\myYun\demo_csharp\.net core3.1 web api 部分组件示例\014_SqlSugar测试sql\Program.cs:line 16

```

**Comment by donet5** [comment]
这个后续完善

**Comment by h619633675** [comment]
emmm...... 好的

**Comment by donet5** [comment]
已解决

**Comment by h619633675** [comment]
您好,需要麻烦您解答一下, 是怎么使用解决这个问题的,刚刚我重新实验了一下同实体查子父,还是一样的报错。
System.ArgumentException:“An item with the same key has already been added. Key: Tree.Id”

```
            var list = db.Queryable<Tree, Tree>((a,b ) => new JoinQueryInfos( JoinType.Inner, a.ParentId == b.Id))
                .Where((a, b) => a.Id == 122)
                .Select((a, b) => new { 
                    user = a, 
                    parentUser = b
                })
                .ToList();

        [SugarColumn(ColumnName = "id", IsPrimaryKey = true)]
        public int Id { get; set; }
        [SugarColumn(ColumnName = "pid")]
        public int ParentId { get; set; }
        [SugarColumn(ColumnName = "name")]
        public string? Name {  get; set;}
```

**Comment by donet5** [comment]
过几天 在发布一个版本，单元测试这个例子确实存在问题

**Comment by h619633675** [comment]
好的，感谢大佬，大佬辛苦了

**Comment by donet5** [comment]
GITHUB下载一个版本在试试

**Comment by h619633675** [comment]
可以了，谢谢大佬，大佬国庆多喝阔落
