### ISSUE TITLE
程序报异常的疑问,不确定什么场景的异常信息,不确定是否因为我哪里错误调用，还是其它原因

### ISSUE THREAD

**Issue by h619633675** [donet5/SqlSugar#912]
我运行的是 .net core 3.1 控制台程序，下面是程序控制台运行的时候,cmd打印出来的信息
```
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      Unhandled exception while processing 0HM8P17QE4VHN.
System.NotSupportedException:  The WriteAsync method cannot be called when another write operation is pending.
   at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeWriter.CompleteAsync(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStreamAdapter`1.DisposeAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConnectionLimitMiddleware.OnConnectionAsync(ConnectionContext connection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.ExecuteAsync()
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      Unhandled exception while processing 0HM8P17QE4VJM.
System.NotSupportedException:  The WriteAsync method cannot be called when another write operation is pending.
   at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeWriter.CompleteAsync(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStreamAdapter`1.DisposeAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConnectionLimitMiddleware.OnConnectionAsync(ConnectionContext connection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.ExecuteAsync()
```

我 google 了一下其中的关键字 
```
The WriteAsync method cannot be called when another write operation is pending.
   at System.Net.Security.SslStream.WriteAsyncInternal
```
打开的第一条搜索条目 https://github.com/mysql-net/MySqlConnector/issues/509

**Comment by donet5** [comment]
这个要看你的代码如何写，用控制台写个最简单的DEMO

**Comment by h619633675** [comment]
没有复现成功，就长期启动时查看着控制台有输出此信息，而我中间件异常捕获，sqlsugar 异常捕获这些都没有记录日志



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月18日(星期二) 中午12:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [donet5/SqlSugar] 程序报异常的疑问,不确定什么场景的异常信息,不确定是否因为我哪里错误调用，还是其它原因 (#912)





 
这个要看你的代码如何写，用控制台写个最简单的DEMO

**Comment by donet5** [comment]
如果DEMO不能重现，那就要去现有代码找原因了，慢慢排除
