### ISSUE TITLE
【CodeFirst】oracle数据库，现在不支持创建联合主键吗？

### ISSUE THREAD

**Issue by sunyu005** [donet5/SqlSugar#944]
你好，在使用CodeFirst创建表时（Oracle数据库），需要使用联合主键，就在Entity类两个属性分别指定了【IsPrimaryKey = true】。在执行时抛出异常了。劳烦帮忙确认一下，是我的用法不对还是不支持这么用？

**Entity代码：**
```
[SugarTable("sys_file")]
public class SysFileEntity
{
    [SugarColumn(IsPrimaryKey = true, ColumnName = "file_grp_id", Length = 100)]
    public string FileGrpId { get; set; }

    [SugarColumn(IsPrimaryKey = true, ColumnName = "file_id", Length = 100)]
    public string FileId { get; set; }

    [SugarColumn(ColumnName = "file_name", Length = 100)]
    public string FileName { get; set; }
}
```

**异常Message：**
SqlSugar.SqlSugarException
  HResult=0x80131500
  Message=ORA-02260:table can have only one primary key
  Source=SqlSugar
  スタック トレース:
   at SqlSugar.Check.Exception(Boolean isException, String message, String[] args)
   at SqlSugar.CodeFirstProvider.InitTables(Type entityType)
   ......

**源码：OracleDbMaintenance.cs**
```
public override bool CreateTable(string tableName, List<DbColumnInfo> columns, bool isCreatePrimaryKey = true)
{
    if (columns.HasValue())
    {
        foreach (var item in columns)
        {
            if (item.DbColumnName.Equals("GUID", StringComparison.CurrentCultureIgnoreCase) && item.Length == 0)
            {
                item.Length = 50;
            }
            if (item.DataType == "varchar" && item.Length == 0)
            {
                item.Length = 50;
            }
        }
    }
    string sql = GetCreateTableSql(tableName, columns);
    this.Context.Ado.ExecuteCommand(sql);
    if (isCreatePrimaryKey)
    {
        var pkColumns = columns.Where(it => it.IsPrimarykey).ToList();
        foreach (var item in pkColumns)
        {
            this.Context.DbMaintenance.AddPrimaryKey(tableName, item.DbColumnName);
        }
    }
    return true;
}
```
上述方法中，如果存在多个主键循环执行创建主键的Sql脚本，而Oracle中不支持这种创建主键方式吧。
还是说不考虑支持Oracle联合主键。

**Comment by donet5** [comment]
db.CodeFirst.InitTables<SysFileEntity>()  这样是支持多主键的，不过不支持修改主键 ，删 掉现有表执行看看

**Comment by donet5** [comment]
确实存在这个BUG 下个版本修复

**Comment by sunyu005** [comment]
好的，谢谢 辛苦了。
看源码与SqlServerDbMaintenance.cs和MySqlDbMaintenance.cs的CreateTable方法写法不一致。
还有一个问题，NuGet跟GitHub中Tag的版本号对不上啊？
